### PR TITLE
Adding "defaultprevalence"

### PR DESCRIPTION
**Pull request by xavi-rp**
I have modified ENMevaluate.R and make.args.R in order to be able to modify the parameter "prevalence" to be passed to maxent.
The default value is still 0.5, but it can be modified, if necessary, when you call the function ENMevaluate.
I would very much appreciate any comment you can do to this modification.
Thanks.
Xavier Rotllan-Puig

### CODE REVIEW

**Comment by ndimhypervol** [comment]
Thanks for the edits, but I think to avoid adding too many extra parameters, we might want to simply add a "..." parameter to allow users to input any maxent-related parameter they'd like. There are many others that people might want to alter too.

**Comment by xavi-rp** [comment]
Thanks for your reply.
I agree that it's better to have the possibility of modifying any maxent-related parameter, not just prevalence.
Thanks again.

**Comment by ndimhypervol** [comment]
Yeah, thanks for calling this to our attention. I think it's an important thing we overlooked.

**Comment by ndimhypervol** [comment]
We're in the process of adding a "..." argument to the main function that will let you add any other Maxent params you wish. Will let you know when we're done.

**Pull request closed without merging**
